### ISSUE TITLE
Need to understand and document in our instructions how to split a line for a tunnel rather than trace over. 

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#16] opened 2021-09-24 18:14 UTC
Plz add to user instructions. 

If it's unclear how this is done, we can get another tutorial from Jimmy.

**Comment by jessbeutler** [comment] 2021-10-05 19:17
@GDMatthews I believe this is a duplicate of issue #8 - please confirm if this is the case. If so, I will merge issues. If not, please let me know what the difference is.

**Comment by jessbeutler** [comment] 2021-10-12 19:51
## Re-write of instructions

**Read all instructions before proceeding:**

### Project Specific Mapping Notes
* Available tasks to map may be difficult to view and select individually. Instead, rely on automatic task selection by the TM until project is completed to ensure full coverage.

* Mapping tasks are designed to be buffers around segments of railroad features. This results in abnormal, and often disconnected, mapping task shapes.

* **Individual project tasks may be larger than they appear when first loaded in iD Editor. Make sure to zoom out to see the full extent of the mapping project before completing.**

* **Imagery:** You are encouraged to use different Background imagery options to compare features at different times of the day or from dissimilar satellite locations.   

### Getting started with your Mapping Task
1. Start by clicking **Map a Task** in the lower right-hand corner of the TM window below the map. 
2. The iD editor will load with the mapping task boundary in magenta. Zoom out to see the full extent of this segment.  

![zoom_instruction](https://github.com/publicdomainmap/public_files/blob/main/TM_instructions_images/TM_rrtunnel_instructions1-1.gif?raw=true)

3. *(Optional)* If the size is too large to complete in one sitting, go to the right-hand panel and scroll to the bottom.  Click the **Split task** button. This pulls you out of editor mode back to the Tasking Manager. Start again by clicking **Map a Task** in the lower right-hand corner of the TM window below the map. 

4. After surveying the task to understand the mapping extent, open the "Map Data" settings menu on the right of the map and *temporarily* turn off "PublicDomainMap data" so you can see the USGS imagery clearly.  **Do NOT turn of "Custom Map Data".**

![turnoffdata_instruction](https://github.com/publicdomainmap/public_files/blob/main/TM_instructions_images/TM_rrtunnel_instructions2.gif?raw=true)

5. Open the "Background" settings menu, view the various imagery options to determine the clearest option for mapping. *(National Agriculture Imagery Program is recommended for this project.)*

6. Begin searching for tunnels. Start at the edge of the grid and view the railroad in one direction. A tunnel will be an earthen underpass or located under a building; *it will not be under a man-made bridge*.  

**If you find a tunnel to map,** continue to the "Mapping Railroad Tunnels" instructions below to add the feature. 

**Or else,** in the right-hand panel mark the task as Completely Mapped = Yes, add a comment: "No tunnels found", and then submit the task.

![tunnel searching_instruction](https://github.com/publicdomainmap/public_files/blob/main/TM_instructions_images/TM_rrtunnel_instructions3-1.gif?raw=true)
 
### Mapping Railroad Tunnels
1. When you find a tunnel, turn PublicDomainMap data features back on before proceeding to map the tunnel. 
1. Select the railroad line feature. It will flash red when it is properly selected.  
2. Zoom in closely to map the tunnel opening accurately. Hover over the point of the line where the tunnel begins. Double-click to create a node on the line. 
3. Right-click on the node and select the "Split" option (indicated by a scissor icon).

![split line_instruction](https://raw.githubusercontent.com/publicdomainmap/public_files/main/TM_instructions_images/TM_rrtunnel_instructions4.gif)

3. Navigate to where the tunnel ends. Repeat steps 2 & 3 above to split the line. 
4. Select the tunnel segment. This should flash red, separate from the rest of the railroad feature. 

![full_tunnel](https://github.com/publicdomainmap/public_files/blob/main/TM_instructions_images/TM_rrtunnel_instructions5-698.png?raw=true)

5. On the left hand panel, under "Fields" select the "Structure" type as "Tunnel". This will add the tunnel=yes tag to the feature. 

![tagging](https://raw.githubusercontent.com/publicdomainmap/public_files/main/TM_instructions_images/TM_rrtunnel_instructions6.png)

6. Congrats! You've mapped a tunnel. Upload your work periodically by clicking Save at the top of the map.  
7. When you're done, go to the right pane and update the Task Status with Yes (completed all tunnels) or No (didn’t check for all tunnels), and add a Comment (e.g. I added three tunnels).  
8. Click the Submit task button to finish.

**Comment by jessbeutler** [comment] 2021-10-12 19:52
You can preview them in the TM here: https://tm.publicdomainmap.org/projects/25/tasks

**Comment by jessbeutler** [comment] 2021-10-19 16:03
@GDMatthews - Please review these instructions when you have the time. Let me know if there's anything I should clarify.

**Comment by GDMatthews** [comment] 2021-10-19 21:14
Hi Jess, I’ve reviewed your instructions for editing. 

You have the instructions updated for task #25 which I’ve found the link for in the GitHub issue here https://tm.publicdomainmap.org/projects/25/tasks. Should that also be showing up withing our projects below? I’m just noting with the screen capture below that it doesn’t show up. 

I’ll continue to work through the instructions and think about different scenarios but for now, I think it would be good to have the instructions set up like “if then, or else” logic. So if you find a tunnel to map in the area checked out, use the following instruction to add the feature. Or else, mark the task as Completely Mapped = Yes, add a comment and then submit the task.  

I have other ideas and thoughts but they may be out of scope for this particular task and I’ll comment on those later.

Thanks - Greg

![image](https://user-images.githubusercontent.com/85766403/137991397-a11aa088-b555-4805-86e5-fb26bd6617a8.png)

**Comment by jessbeutler** [comment] 2021-11-02 12:57
@GDMatthews - yes, I kept project 25 in draft. Still could be found by the link but not showing up in the main page. 

I've updated the instructions per your recommendations. Let me know if this makes more sense/ is in line with what you were looking for. I will update all projects once we're okay with the instructions.

**Comment by jessbeutler** [comment] 2021-11-09 22:44
Project instructions added to all ACTIVE projects.

**Closed as completed by jessbeutler** 2021-11-09 22:44 UTC
Labels: documentation
