### ISSUE TITLE
Instructions need updated

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#8] opened 2021-09-16 18:30 UTC
After editing several tasks, I believe the instructions aren't synced up with what you're seeing in the interface. This may need some minor text editing to make sure text reflects what's on the screen. 

The instructions direct the editor to create a new line for railroad tunnels. I'll confirm with Jimmy but I believe we want to split the railroad line feature at the tunnels rather than create a new line segment. Text should be updated to reflect this.

**Comment by GDMatthews** [comment] 2021-10-05 19:29
Confirming this is a duplicate issue. Greg

**Comment by jessbeutler** [comment] 2021-10-05 19:34
Closing this issue as it is a duplicate of #16

**Closed as completed by jessbeutler** 2021-10-05 19:34 UTC
Labels: documentation
